# preload = ~/Pictures/Wallpapers/catppuccin.jpg
# wallpaper = , ~/Pictures/Wallpapers/catppuccin.jpg

# preload = ~/Pictures/Wallpapers/anime_skull.png
# wallpaper = , ~/Pictures/Wallpapers/anime_skull.png

preload = ~/Pictures/Wallpapers/Arch_gruvbox.png
wallpaper= , ~/Pictures/Wallpapers/Arch_gruvbox.png
